// <auto-generated />
using System;
using Hotel_CodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel_CodeFirst.Migrations
{
    [DbContext(typeof(Hotel))]
    [Migration("20240128144443_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hotel_CodeFirst.Models.Cliente", b =>
                {
                    b.Property<int>("Codigo_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Cliente"));

                    b.Property<string>("Nacionalidade_Cliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome_Cliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Codigo_Cliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.ConsumoFrigobar", b =>
                {
                    b.Property<int>("Codigo_ConsumoFrigobar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_ConsumoFrigobar"));

                    b.Property<int>("ContaReservaCodigo_ContaReserva")
                        .HasColumnType("int");

                    b.Property<int>("FrigobarCodigo_Frigobar")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Codigo_ConsumoFrigobar");

                    b.HasIndex("ContaReservaCodigo_ContaReserva");

                    b.HasIndex("FrigobarCodigo_Frigobar");

                    b.ToTable("ConsumoFrigobares");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.ConsumoLavanderia", b =>
                {
                    b.Property<int>("Codigo_ConsumoLavanderia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_ConsumoLavanderia"));

                    b.Property<int>("ContaReservaCodigo_ContaReserva")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("ServicoLavanderiaCodigo_ServicoLavanderia")
                        .HasColumnType("int");

                    b.HasKey("Codigo_ConsumoLavanderia");

                    b.HasIndex("ContaReservaCodigo_ContaReserva");

                    b.HasIndex("ServicoLavanderiaCodigo_ServicoLavanderia");

                    b.ToTable("ConsumosLavanderia");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.ConsumoRestaurante", b =>
                {
                    b.Property<int>("Codigo_ConsumoRestaurante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_ConsumoRestaurante"));

                    b.Property<int>("ContaReservaCodigo_ContaReserva")
                        .HasColumnType("int");

                    b.Property<bool>("EntregueNoQuarto")
                        .HasColumnType("bit");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("RestauranteCodigo_Restaurante")
                        .HasColumnType("int");

                    b.HasKey("Codigo_ConsumoRestaurante");

                    b.HasIndex("ContaReservaCodigo_ContaReserva");

                    b.HasIndex("RestauranteCodigo_Restaurante");

                    b.ToTable("ConsumoRestaurantes");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.ContaReserva", b =>
                {
                    b.Property<int>("Codigo_ContaReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_ContaReserva"));

                    b.Property<decimal>("ValorGasto_ContaReserva")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo_ContaReserva");

                    b.ToTable("ContasReserva");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Endereco", b =>
                {
                    b.Property<int>("Codigo_Endereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Endereco"));

                    b.Property<string>("Bairro_Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cidade_Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ClienteCodigo_Cliente")
                        .HasColumnType("int");

                    b.Property<string>("Complemento_Endereco")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Estado_Endereco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Numero_Endereco")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Pais_Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rua_Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Codigo_Endereco");

                    b.HasIndex("ClienteCodigo_Cliente");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Filial", b =>
                {
                    b.Property<int>("Codigo_Filial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Filial"));

                    b.Property<string>("Endereco_Filial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_Filial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroQuartos_Filial")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeEstrelas_Filial")
                        .HasColumnType("int");

                    b.HasKey("Codigo_Filial");

                    b.ToTable("Filiais");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Frigobar", b =>
                {
                    b.Property<int>("Codigo_Frigobar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Frigobar"));

                    b.Property<string>("Nome_ItemFrigobar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco_ItemFrigobar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo_Frigobar");

                    b.ToTable("Frigobares");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Funcionario", b =>
                {
                    b.Property<int>("Codigo_Funcionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Funcionario"));

                    b.Property<string>("Nome_Funcionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoFuncionarioCodigo_TipoFuncionario")
                        .HasColumnType("int");

                    b.HasKey("Codigo_Funcionario");

                    b.HasIndex("TipoFuncionarioCodigo_TipoFuncionario");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.NotaFiscal", b =>
                {
                    b.Property<int>("Codigo_NotaFiscal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_NotaFiscal"));

                    b.Property<DateTime>("Data_NotaFiscal")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numero_NotaFiscal")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("TipoPagamentoCodigo_TipoPagamento")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal_NotaFiscal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo_NotaFiscal");

                    b.HasIndex("TipoPagamentoCodigo_TipoPagamento");

                    b.ToTable("NotaFiscais");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Quarto", b =>
                {
                    b.Property<string>("Numero_Quarto")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("FilialCodigo_Filial")
                        .HasColumnType("int");

                    b.Property<int>("TipoQuartoCodigo_TipoQuarto")
                        .HasColumnType("int");

                    b.HasKey("Numero_Quarto");

                    b.HasIndex("FilialCodigo_Filial");

                    b.HasIndex("TipoQuartoCodigo_TipoQuarto");

                    b.ToTable("Quartos");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Reserva", b =>
                {
                    b.Property<int>("Codigo_Reserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Reserva"));

                    b.Property<bool>("Cancelada_Reserva")
                        .HasColumnType("bit");

                    b.Property<int>("ClienteCodigo_Cliente")
                        .HasColumnType("int");

                    b.Property<int>("ContaReservaCodigo_ContaReserva")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim_Reserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio_Reserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("NotaFiscalCodigo_NotaFiscal")
                        .HasColumnType("int");

                    b.Property<string>("Numero_Quarto")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("QuartoNumero_Quarto")
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Codigo_Reserva");

                    b.HasIndex("ClienteCodigo_Cliente");

                    b.HasIndex("ContaReservaCodigo_ContaReserva");

                    b.HasIndex("NotaFiscalCodigo_NotaFiscal");

                    b.HasIndex("QuartoNumero_Quarto");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Restaurante", b =>
                {
                    b.Property<int>("Codigo_Restaurante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Restaurante"));

                    b.Property<string>("Nome_ItemMenu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco_ItemMenu")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo_Restaurante");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.ServicoLavanderia", b =>
                {
                    b.Property<int>("Codigo_ServicoLavanderia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_ServicoLavanderia"));

                    b.Property<string>("Descricao_ServicoLavanderia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco_ServicoLavanderia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo_ServicoLavanderia");

                    b.ToTable("ServicosLavanderia");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Telefone", b =>
                {
                    b.Property<int>("Codigo_Telefone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Telefone"));

                    b.Property<int>("ClienteCodigo_Cliente")
                        .HasColumnType("int");

                    b.Property<string>("Numero_Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Codigo_Telefone");

                    b.HasIndex("ClienteCodigo_Cliente");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.TipoFuncionario", b =>
                {
                    b.Property<int>("Codigo_TipoFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_TipoFuncionario"));

                    b.Property<string>("Desc_TipoFuncionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo_TipoFuncionario");

                    b.ToTable("TipoFuncionarios");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.TipoPagamento", b =>
                {
                    b.Property<int>("Codigo_TipoPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_TipoPagamento"));

                    b.Property<string>("Desc_TipoPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Codigo_TipoPagamento");

                    b.ToTable("TipoPagementos");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.TipoQuarto", b =>
                {
                    b.Property<int>("Codigo_TipoQuarto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_TipoQuarto"));

                    b.Property<string>("Desc_TipoQuarto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Valor_TipoQuarto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo_TipoQuarto");

                    b.ToTable("TipoQuartos");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.ConsumoFrigobar", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.ContaReserva", "ContaReserva")
                        .WithMany()
                        .HasForeignKey("ContaReservaCodigo_ContaReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_CodeFirst.Models.Frigobar", "Frigobar")
                        .WithMany()
                        .HasForeignKey("FrigobarCodigo_Frigobar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaReserva");

                    b.Navigation("Frigobar");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.ConsumoLavanderia", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.ContaReserva", "ContaReserva")
                        .WithMany()
                        .HasForeignKey("ContaReservaCodigo_ContaReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_CodeFirst.Models.ServicoLavanderia", "ServicoLavanderia")
                        .WithMany()
                        .HasForeignKey("ServicoLavanderiaCodigo_ServicoLavanderia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaReserva");

                    b.Navigation("ServicoLavanderia");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.ConsumoRestaurante", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.ContaReserva", "ContaReserva")
                        .WithMany()
                        .HasForeignKey("ContaReservaCodigo_ContaReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_CodeFirst.Models.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteCodigo_Restaurante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaReserva");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Endereco", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCodigo_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Funcionario", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.TipoFuncionario", "TipoFuncionario")
                        .WithMany()
                        .HasForeignKey("TipoFuncionarioCodigo_TipoFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoFuncionario");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.NotaFiscal", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.TipoPagamento", "TipoPagamento")
                        .WithMany()
                        .HasForeignKey("TipoPagamentoCodigo_TipoPagamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoPagamento");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Quarto", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.Filial", null)
                        .WithMany("Quartos")
                        .HasForeignKey("FilialCodigo_Filial");

                    b.HasOne("Hotel_CodeFirst.Models.TipoQuarto", "TipoQuarto")
                        .WithMany()
                        .HasForeignKey("TipoQuartoCodigo_TipoQuarto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoQuarto");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Reserva", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCodigo_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_CodeFirst.Models.ContaReserva", "ContaReserva")
                        .WithMany()
                        .HasForeignKey("ContaReservaCodigo_ContaReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_CodeFirst.Models.NotaFiscal", "NotaFiscal")
                        .WithMany()
                        .HasForeignKey("NotaFiscalCodigo_NotaFiscal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_CodeFirst.Models.Quarto", "Quarto")
                        .WithMany()
                        .HasForeignKey("QuartoNumero_Quarto");

                    b.Navigation("Cliente");

                    b.Navigation("ContaReserva");

                    b.Navigation("NotaFiscal");

                    b.Navigation("Quarto");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Telefone", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCodigo_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Filial", b =>
                {
                    b.Navigation("Quartos");
                });
#pragma warning restore 612, 618
        }
    }
}
