// <auto-generated />
using System;
using Hotel_CodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel_CodeFirst.Migrations
{
    [DbContext(typeof(Hotel))]
    partial class HotelModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hotel_CodeFirst.Models.Cliente", b =>
                {
                    b.Property<int>("Codigo_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Cliente"));

                    b.Property<string>("Nacionalidade_Cliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome_Cliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Codigo_Cliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.ConsumoFrigobar", b =>
                {
                    b.Property<int>("Codigo_ConsumoFrigobar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_ConsumoFrigobar"));

                    b.Property<int>("Codigo_ContaReserva")
                        .HasColumnType("int");

                    b.Property<int>("Codigo_Frigobar")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Codigo_ConsumoFrigobar");

                    b.HasIndex("Codigo_ContaReserva");

                    b.HasIndex("Codigo_Frigobar");

                    b.ToTable("ConsumoFrigobares");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.ConsumoLavanderia", b =>
                {
                    b.Property<int>("Codigo_ConsumoLavanderia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_ConsumoLavanderia"));

                    b.Property<int>("Codigo_ContaReserva")
                        .HasColumnType("int");

                    b.Property<int>("Codigo_ServicoLavanderia")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Codigo_ConsumoLavanderia");

                    b.HasIndex("Codigo_ContaReserva");

                    b.HasIndex("Codigo_ServicoLavanderia");

                    b.ToTable("ConsumosLavanderia");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.ConsumoRestaurante", b =>
                {
                    b.Property<int>("Codigo_ConsumoRestaurante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_ConsumoRestaurante"));

                    b.Property<int>("Codigo_ContaReserva")
                        .HasColumnType("int");

                    b.Property<int>("Codigo_Restaurante")
                        .HasColumnType("int");

                    b.Property<bool>("EntregueNoQuarto")
                        .HasColumnType("bit");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Codigo_ConsumoRestaurante");

                    b.HasIndex("Codigo_ContaReserva");

                    b.HasIndex("Codigo_Restaurante");

                    b.ToTable("ConsumoRestaurantes");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.ContaReserva", b =>
                {
                    b.Property<int>("Codigo_ContaReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_ContaReserva"));

                    b.Property<decimal>("ValorGasto_ContaReserva")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo_ContaReserva");

                    b.ToTable("ContasReserva");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Email", b =>
                {
                    b.Property<int>("Codigo_Email")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Email"));

                    b.Property<int>("Codigo_Cliente")
                        .HasColumnType("int");

                    b.Property<string>("Endereco_Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Codigo_Email");

                    b.HasIndex("Codigo_Cliente");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Endereco", b =>
                {
                    b.Property<int>("Codigo_Endereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Endereco"));

                    b.Property<string>("Bairro_Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cidade_Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Codigo_Cliente")
                        .HasColumnType("int");

                    b.Property<string>("Complemento_Endereco")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Estado_Endereco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Numero_Endereco")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Pais_Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rua_Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Codigo_Endereco");

                    b.HasIndex("Codigo_Cliente");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Filial", b =>
                {
                    b.Property<int>("Codigo_Filial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Filial"));

                    b.Property<string>("Endereco_Filial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_Filial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroQuartos_Filial")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeEstrelas_Filial")
                        .HasColumnType("int");

                    b.HasKey("Codigo_Filial");

                    b.ToTable("Filiais");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Frigobar", b =>
                {
                    b.Property<int>("Codigo_Frigobar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Frigobar"));

                    b.Property<string>("Nome_ItemFrigobar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco_ItemFrigobar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo_Frigobar");

                    b.ToTable("Frigobares");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Funcionario", b =>
                {
                    b.Property<int>("Codigo_Funcionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Funcionario"));

                    b.Property<int>("Codigo_TipoFuncionario")
                        .HasColumnType("int");

                    b.Property<string>("Nome_Funcionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo_Funcionario");

                    b.HasIndex("Codigo_TipoFuncionario");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.NotaFiscal", b =>
                {
                    b.Property<int>("Codigo_NotaFiscal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_NotaFiscal"));

                    b.Property<int>("Codigo_TipoPagamento")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data_NotaFiscal")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numero_NotaFiscal")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<decimal>("ValorTotal_NotaFiscal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo_NotaFiscal");

                    b.HasIndex("Codigo_TipoPagamento");

                    b.ToTable("NotaFiscais");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Quarto", b =>
                {
                    b.Property<int>("Numero_Quarto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Numero_Quarto"));

                    b.Property<int>("Codigo_Filial")
                        .HasColumnType("int");

                    b.Property<int>("Codigo_TipoQuarto")
                        .HasColumnType("int");

                    b.HasKey("Numero_Quarto");

                    b.HasIndex("Codigo_Filial");

                    b.HasIndex("Codigo_TipoQuarto");

                    b.ToTable("Quartos");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Reserva", b =>
                {
                    b.Property<int>("Codigo_Reserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Reserva"));

                    b.Property<bool>("Cancelada_Reserva")
                        .HasColumnType("bit");

                    b.Property<int>("Codigo_Cliente")
                        .HasColumnType("int");

                    b.Property<int?>("Codigo_ContaReserva")
                        .HasColumnType("int");

                    b.Property<int?>("Codigo_NotaFiscal")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim_Reserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio_Reserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("Numero_Quarto")
                        .HasColumnType("int");

                    b.HasKey("Codigo_Reserva");

                    b.HasIndex("Codigo_Cliente");

                    b.HasIndex("Codigo_ContaReserva");

                    b.HasIndex("Codigo_NotaFiscal");

                    b.HasIndex("Numero_Quarto");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Restaurante", b =>
                {
                    b.Property<int>("Codigo_Restaurante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Restaurante"));

                    b.Property<string>("Nome_ItemMenu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco_ItemMenu")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo_Restaurante");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.ServicoLavanderia", b =>
                {
                    b.Property<int>("Codigo_ServicoLavanderia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_ServicoLavanderia"));

                    b.Property<string>("Descricao_ServicoLavanderia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco_ServicoLavanderia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo_ServicoLavanderia");

                    b.ToTable("ServicosLavanderia");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Telefone", b =>
                {
                    b.Property<int>("Codigo_Telefone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Telefone"));

                    b.Property<int>("Codigo_Cliente")
                        .HasColumnType("int");

                    b.Property<string>("Numero_Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Codigo_Telefone");

                    b.HasIndex("Codigo_Cliente");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.TipoFuncionario", b =>
                {
                    b.Property<int>("Codigo_TipoFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_TipoFuncionario"));

                    b.Property<string>("Desc_TipoFuncionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo_TipoFuncionario");

                    b.ToTable("TipoFuncionarios");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.TipoPagamento", b =>
                {
                    b.Property<int>("Codigo_TipoPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_TipoPagamento"));

                    b.Property<string>("Desc_TipoPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Codigo_TipoPagamento");

                    b.ToTable("TipoPagementos");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.TipoQuarto", b =>
                {
                    b.Property<int>("Codigo_TipoQuarto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_TipoQuarto"));

                    b.Property<string>("Desc_TipoQuarto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Valor_TipoQuarto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo_TipoQuarto");

                    b.ToTable("TipoQuartos");
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.ConsumoFrigobar", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.ContaReserva", null)
                        .WithMany()
                        .HasForeignKey("Codigo_ContaReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hotel_CodeFirst.Models.Frigobar", null)
                        .WithMany()
                        .HasForeignKey("Codigo_Frigobar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.ConsumoLavanderia", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.ContaReserva", null)
                        .WithMany()
                        .HasForeignKey("Codigo_ContaReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hotel_CodeFirst.Models.ServicoLavanderia", null)
                        .WithMany()
                        .HasForeignKey("Codigo_ServicoLavanderia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.ConsumoRestaurante", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.ContaReserva", null)
                        .WithMany()
                        .HasForeignKey("Codigo_ContaReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hotel_CodeFirst.Models.Restaurante", null)
                        .WithMany()
                        .HasForeignKey("Codigo_Restaurante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Email", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.Cliente", null)
                        .WithMany()
                        .HasForeignKey("Codigo_Cliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Endereco", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.Cliente", null)
                        .WithMany()
                        .HasForeignKey("Codigo_Cliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Funcionario", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.TipoFuncionario", null)
                        .WithMany()
                        .HasForeignKey("Codigo_TipoFuncionario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.NotaFiscal", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.TipoPagamento", null)
                        .WithMany()
                        .HasForeignKey("Codigo_TipoPagamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Quarto", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.Filial", null)
                        .WithMany()
                        .HasForeignKey("Codigo_Filial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hotel_CodeFirst.Models.TipoQuarto", null)
                        .WithMany()
                        .HasForeignKey("Codigo_TipoQuarto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Reserva", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.Cliente", null)
                        .WithMany()
                        .HasForeignKey("Codigo_Cliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hotel_CodeFirst.Models.ContaReserva", null)
                        .WithMany()
                        .HasForeignKey("Codigo_ContaReserva")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Hotel_CodeFirst.Models.ContaReserva", null)
                        .WithMany()
                        .HasForeignKey("Codigo_NotaFiscal")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hotel_CodeFirst.Models.Quarto", null)
                        .WithMany()
                        .HasForeignKey("Numero_Quarto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hotel_CodeFirst.Models.Telefone", b =>
                {
                    b.HasOne("Hotel_CodeFirst.Models.Cliente", null)
                        .WithMany()
                        .HasForeignKey("Codigo_Cliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
